teleop_cpp_node:
  ros__parameters:
    use_sim_time: true
    throttle_axis: 2
    steering_axis: 3
    braking_axis: 5
    estop_button: 1
joy_node:
  ros__parameters: 
    device_id: 0
    device_name: "Generic X-Box pad"
    deadzone: 0.05
    autorepeat_rate: 0.0
    sticky_buttons: true
    coalesce_interval_ms: 1